name: ci
on: [push]

jobs:
  testWithOwnerAndBranch:  # will create a pr to update existing file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: sync
        uses: ./
        with:
          repositories: 'solubris/insync-dst@master'
          token: ${{ secrets.INSYNC_DST_TOKEN }}
          files: .gitignore
          pr-branch: ${{ github.job }}
      - name: setup env
        run: |
          echo "::set-output name=DST_PATH::$(mktemp -d /tmp/insync-dst.XXXXXX)"
        id: env
      - name: checkout the dst repo
        run: |
          cd "${{ steps.env.outputs.DST_PATH }}"
          git clone "https://none:${{ secrets.INSYNC_DST_TOKEN }}@github.com/solubris/insync-dst.git" .
      - name: remove the branch created during test
        run: |
          cd "${{ steps.env.outputs.DST_PATH }}"
          git push -d origin ${{ github.job }}
  testUpdate:  # will create a pr to update existing file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: sync
        uses: ./
        with:
          repositories: 'insync-dst'
          token: ${{ secrets.INSYNC_DST_TOKEN }}
          files: .gitignore
          pr-branch: testUpdate
      - name: remove the branch created during test
        run: |
          DST_PATH="$(mktemp -d /tmp/insync-dst.XXXXXX)"
          cd "$DST_PATH"
          git clone "https://none:${{ secrets.INSYNC_DST_TOKEN }}@github.com/solubris/insync-dst.git" .
          git push -d origin testUpdate
  testCopy:  # will create a pr to copy over a new file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: sync
        uses: ./
        with:
          repositories: 'insync-dst'
          token: ${{ secrets.INSYNC_DST_TOKEN }}
          files: .editorconfig
          pr-branch: testCopy
      - name: check the files exist in the dst repo
        run: |
          DST_PATH="$(mktemp -d /tmp/insync-dst.XXXXXX)"
          cd "$DST_PATH"
          git clone "https://none:${{ secrets.INSYNC_DST_TOKEN }}@github.com/solubris/insync-dst.git" .
          git checkout testCopy
          ls .editorconfig
      - name: remove the branch created during test
        run: |
          DST_PATH="$(mktemp -d /tmp/insync-dst.XXXXXX)"
          cd "$DST_PATH"
          git clone "https://none:${{ secrets.INSYNC_DST_TOKEN }}@github.com/solubris/insync-dst.git" .
          git push -d origin testCopy
  testDelete:  # will create a pr to delete file from dst
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: sync
        uses: ./
        with:
          repositories: 'insync-dst'
          token: ${{ secrets.INSYNC_DST_TOKEN }}
          files: .dummyFileForTest
          pr-branch: testDelete
      - name: check the file does not exist in the dst repo
        run: |
          DST_PATH="$(mktemp -d /tmp/insync-dst.XXXXXX)"
          cd "$DST_PATH"
          git clone "https://none:${{ secrets.INSYNC_DST_TOKEN }}@github.com/solubris/insync-dst.git" .
          git checkout testDelete
          if [ -e .dummyFileForTest ]; then
            echo .dummyFileForTest was not deleted
            exit 1
          fi
          export GITHUB_TOKEN=${{ secrets.INSYNC_DST_TOKEN }}
          openPrs=$(hub pr list -s open -h testDelete | wc -l)
          if [ "$openPrs" -eq 0 ]; then
            echo no pr was opened
            exit 1
          fi
      - name: remove the branch created during test
        run: |
          DST_PATH="$(mktemp -d /tmp/insync-dst.XXXXXX)"
          cd "$DST_PATH"
          git clone "https://none:${{ secrets.INSYNC_DST_TOKEN }}@github.com/solubris/insync-dst.git" .
          git push -d origin testDelete
  testUpdateWithExistingBranch:  # will update existing branch/pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: sync
        uses: ./
        with:
          repositories: 'insync-dst'
          token: ${{ secrets.INSYNC_DST_TOKEN }}
          files: .gitignore
          pr-branch: testUpdateWithExistingBranch
      - name: sync
        uses: ./
        with:
          repositories: 'insync-dst'
          token: ${{ secrets.INSYNC_DST_TOKEN }}
          files: .gitignore .dummyFileForTest
          pr-branch: testUpdateWithExistingBranch
      - name: remove the branch created during test
        run: |
          DST_PATH="$(mktemp -d /tmp/insync-dst.XXXXXX)"
          cd "$DST_PATH"
          git clone "https://none:${{ secrets.INSYNC_DST_TOKEN }}@github.com/solubris/insync-dst.git" .
          git push -d origin testUpdateWithExistingBranch
  testUpdateDir:  # will create a pr to update existing file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: sync
        uses: ./
        with:
          repositories: 'insync-dst'
          token: ${{ secrets.INSYNC_DST_TOKEN }}
          files: src
          pr-branch: testUpdateDir
      - name: remove the branch created during test
        run: |
          DST_PATH="$(mktemp -d /tmp/insync-dst.XXXXXX)"
          cd "$DST_PATH"
          git clone "https://none:${{ secrets.INSYNC_DST_TOKEN }}@github.com/solubris/insync-dst.git" .
          git push -d origin testUpdateDir
  testCopyWithSubdir:  # will create a pr to copy over a new file and creating the subdir's
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: sync
        uses: ./
        with:
          repositories: 'insync-dst'
          token: ${{ secrets.INSYNC_DST_TOKEN }}
          files: src/main/sh/run.sh
          pr-branch: testCopyWithSubdir
      - name: check the files exist in the dst repo
        run: |
          DST_PATH="$(mktemp -d /tmp/insync-dst.XXXXXX)"
          cd "$DST_PATH"
          git clone "https://none:${{ secrets.INSYNC_DST_TOKEN }}@github.com/solubris/insync-dst.git" .
          git checkout testCopyWithSubdir
          ls src/main/sh/run.sh
      - name: remove the branch created during test
        run: |
          DST_PATH="$(mktemp -d /tmp/insync-dst.XXXXXX)"
          cd "$DST_PATH"
          git clone "https://none:${{ secrets.INSYNC_DST_TOKEN }}@github.com/solubris/insync-dst.git" .
          git push -d origin testCopyWithSubdir
